repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        files: ^src/pyfieldml/
        additional_dependencies:
          - "lxml>=5.0"
          - "numpy>=1.26"
          - "h5py>=3.10"
          - "scipy>=1.11"
          - "pytest>=8"

  - repo: https://github.com/kynan/nbstripout
    rev: 0.7.1
    hooks:
      - id: nbstripout
